name: Build APK

on:
  push:
    branches: [ "*" ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  pull_request:
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        BUILD_ROOT: ${{github.workspace}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      
      - name: Set up Signing Key
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore
          echo "storeFile=../keystore" > signing.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> signing.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> signing.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> signing.properties
          
      - name: Grant Execute Permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Update glslang external sources
        working-directory: ${{env.BUILD_ROOT}}/core/MobileGL/3rdparty/glslang
        run: |
          python3 update_glslang_sources.py
      
      - name: Build with Gradle and Find APK
        id: build
        run: |
          ./gradlew assembleRelease
          echo "APK=$(find ./app/build/outputs/apk -name "*.apk")" >> $GITHUB_OUTPUT
      
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.APK }}
          archive: false
