name: Build APK

on:
  push:
    branches: [ "*" ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      Release:
        type: boolean
        description: "是否发布一个Release？Should a release be issued?"
        required: true
        default: false

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
      
      - name: Set up Signing Key
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore
          echo "storeFile=../keystore" > signing.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> signing.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> signing.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> signing.properties
          
      - name: Grant Execute Permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle and Find APK
        id: build
        run: |
          ./gradlew assembleRelease
          echo "APK=$(find ./app/build/outputs/apk -name "*.apk")" >> $GITHUB_OUTPUT
      
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.APK }}
          archive: false
          
      - name: Delete Old nightly Release and Tag
        if: ${{ github.event.inputs.Release == 'true' || !contains(github.event.head_commit.message, '[skip delete]') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git tag --list nightly)
          gh release delete "$LATEST_TAG" --yes || echo "No previous nightly release found to delete."
          git push origin --delete "$LATEST_TAG" || echo "No previous nightly tag found to delete."
          
      - name: Create latest Release
        if: ${{ github.event.inputs.Release == 'true' || !contains(github.event.head_commit.message, '[skip release]') }}
        uses: softprops/action-gh-release@v2
        with:
          name: "Nightly Build"
          tag_name: "nightly"
          target_commitish: ${{ github.sha }}
          body: |
            Nightly Build
          files: ${{ steps.build.outputs.APK }}
